import { Users, Brain, Fingerprint, Sparkles, Layers } from "lucide-react";

// site configuration
export const siteConfig = {
  name: "Not A Ghostwriter",
  description:
    "Generate authentic content that matches your unique writing style and voice with our advanced AI platform.",
  url: "https://notaghostwriter.vercel.app",
  ogImage: "https://notaghostwriter.vercel.app/og.jpg",
  supportEmail: "support@notaghostwriter.com",
};

// landing page content
export const landingContent = {
  hero: {
    badge: "AI-Powered Content Creation",
    title: "Content that sounds like you wrote it",
    description:
      "Generate authentic content that matches your unique writing style and voice with our advanced AI platform.",
    cta: "Start Free",
  },

  socialProof: {
    title: "Trusted by innovative companies",
    companies: 6,
  },

  features: {
    title: "Features designed for authentic content",
    description:
      "Our platform helps you create content that resonates with your audience and represents your authentic voice.",
    items: [
      {
        icon: Fingerprint,
        title: "Writing Style Analysis",
        description:
          "Our AI learns your unique writing style through detailed analysis of your preferences and examples.",
        benefits: [
          "Capture tone, voice, and engagement style",
          "Preserve your unique personality",
          "Continuously improve with each post",
        ],
        link: "/features/style-analysis",
      },
      {
        icon: Sparkles,
        title: "Multi-Platform Content",
        description:
          "Create authentic content for multiple platforms that drives connection and conversation.",
        benefits: [
          "LinkedIn, Twitter, blog posts, and more",
          "Multiple content lengths and formats",
          "Control over hashtags and CTAs",
        ],
        link: "/features/content-generation",
      },
      {
        icon: Users,
        title: "Enterprise Team Collaboration",
        description:
          "Maintain brand consistency across teams with collaborative tools.",
        benefits: [
          "Share writing profiles across teams",
          "Approval workflows and permissions",
          "Detailed analytics and reporting",
        ],
        link: "/features/enterprise",
      },
    ],
  },

  howItWorks: {
    title: "How it works",
    description:
      "Create content that sounds like you in just three simple steps",
    steps: [
      {
        number: 1,
        title: "Create your profile",
        description:
          "Answer questions about your writing style, tone, and preferences to create your unique profile.",
      },
      {
        number: 2,
        title: "Define your topic",
        description:
          "Enter your topic, keywords, and content preferences in our simple generation interface.",
      },
      {
        number: 3,
        title: "Generate and publish",
        description:
          "Get professionally written content that matches your style, ready to copy and share.",
      },
    ],
  },

  testimonials: {
    title: "What our users say",
    description:
      "Join thousands of professionals who trust Not A Ghostwriter for their content",
    items: [
      {
        id: 1,
        content:
          "Not A Ghostwriter has transformed my content strategy. The AI captures my voice perfectly, and I save hours each week on content creation.",
        name: "Sarah Johnson",
        role: "Marketing Director",
        company: "TechScale Solutions",
        avatar: "/placeholder.svg?height=64&width=64",
        rating: 5,
      },
      {
        id: 2,
        content:
          "The AI perfectly captures my unique writing style. My audience can't tell the difference between content I wrote myself and what was generated by Not A Ghostwriter.",
        name: "David Chen",
        role: "Social Media Manager",
        company: "Growth Ventures Inc.",
        avatar: "/placeholder.svg?height=64&width=64",
        rating: 5,
      },
      {
        id: 3,
        content:
          "As an enterprise with multiple teams, maintaining consistent voice across content was challenging until we found Not A Ghostwriter. Now our entire organization stays on brand.",
        name: "Michelle Roberts",
        role: "Head of Communications",
        company: "Enterprise Global",
        avatar: "/placeholder.svg?height=64&width=64",
        rating: 5,
      },
    ],
  },

  cta: {
    title: "Ready to sound like yourself, without writing it yourself?",
    description:
      "Join thousands of professionals saving time and improving engagement with AI-generated content that captures their authentic voice.",
    primaryCta: "Create Free Account",
    secondaryCta: "Watch Demo",
  },
};

// faq content
export const faqContent = {
  title: "Frequently Asked Questions",
  items: [
    {
      question: "How does Not A Ghostwriter maintain my writing style?",
      answer:
        "Our AI analyzes your writing samples and preferences to generate content that matches your unique voice, tone, and style. The more information you provide in your profile, the better we can match your style.",
    },
    {
      question: "Can I edit the generated content?",
      answer:
        "All generated content is fully editable. You can modify, expand, or refine any part of the text to better suit your needs.",
    },
    {
      question: "How long does it take to generate content?",
      answer:
        "Most content is generated within seconds. However, more complex or longer pieces may take up to a minute to ensure quality and accuracy.",
    },
    {
      question: "Is my data secure?",
      answer:
        "Yes, we take data security seriously. Your writing samples and generated content are encrypted and never shared with third parties.",
    },
    {
      question: "Can I use the generated content commercially?",
      answer:
        "Yes, all content generated by Not A Ghostwriter belongs to you and can be used for any purpose, including commercial use.",
    },
    {
      question: "Do I need to create an account?",
      answer:
        "While you can try basic features without an account, creating a free account allows you to save your writing profile and access additional features like reference content analysis.",
    },
  ],
};

// about page content
export const aboutContent = {
  title: "About Not A Ghostwriter",
  mission:
    "Our mission is to help people create authentic content that truly represents their voice, without the time investment of writing it themselves.",
  story:
    "Not A Ghostwriter was born from a simple observation: creating consistent, high-quality content is time-consuming, but using generic AI often loses the personal touch that makes content engaging. We set out to solve this problem by building an AI that could truly capture and replicate individual writing styles.",
  values: [
    {
      title: "Authenticity",
      description:
        "We believe content should sound like you, even when you didn't write it.",
    },
    {
      title: "Accessibility",
      description:
        "Great content creation tools should be available to everyone, not just enterprises with big budgets.",
    },
    {
      title: "Innovation",
      description:
        "We're constantly improving our AI to better understand and replicate human writing styles.",
    },
    {
      title: "Privacy",
      description:
        "Your data and writing style are yours alone - we never share or sell your information.",
    },
  ],
  team: {
    title: "Our Team",
    description:
      "We're a small, passionate team of AI engineers, content creators, and product designers dedicated to making content creation easier and more authentic.",
  },
};

// feature pages content
export const featureContent = {
  styleAnalysis: {
    title: "Style Analysis",
    description:
      "Our AI learns your unique writing style through detailed profiling to create content that sounds authentically like you.",
    benefits: [
      {
        title: "Unique Voice Capture",
        description: "Identifies your distinctive writing patterns and voice",
        icon: Fingerprint,
      },
      {
        title: "Deep Learning",
        description:
          "Continuously improves with each piece of content you generate",
        icon: Brain,
      },
      {
        title: "Multi-dimensional Analysis",
        description:
          "Examines tone, structure, vocabulary, and engagement style",
        icon: Layers,
      },
      {
        title: "Authentic Results",
        description: "Creates content indistinguishable from your own writing",
        icon: Sparkles,
      },
    ],
  },

  contentGeneration: {
    title: "Content Generation",
    description:
      "Create professional content tailored to your unique writing style in minutes.",
    platforms: [
      "LinkedIn",
      "Twitter/X",
      "Facebook",
      "Instagram",
      "Blog Posts",
      "Email Newsletters",
      "Website Copy",
      "And more...",
    ],
    contentTypes: [
      "Thought Leadership",
      "Industry Updates",
      "Company Announcements",
      "Product Launches",
      "Educational Content",
      "Case Studies",
      "Personal Stories",
      "And more...",
    ],
  },

  enterprise: {
    title: "Enterprise Solutions",
    description:
      "Unified brand voice, team collaboration, and advanced analytics for your entire organization.",
    features: [
      {
        title: "Team Management",
        items: [
          "Role-based access control",
          "Team workspaces",
          "User permissions",
          "Approval workflows",
        ],
      },
      {
        title: "Content Management",
        items: [
          "Shared content library",
          "Content templates",
          "Version history",
          "Content scheduling",
        ],
      },
      {
        title: "Enterprise Security",
        items: [
          "SOC 2 compliance",
          "SSO integration",
          "Data encryption",
          "Audit logs",
        ],
      },
    ],
  },
};
