import Link from "next/link";
import Image from "next/image";
import {
  ArrowRight,
  Check,
  Users,
  BarChart2,
  Shield,
  Award,
  Star,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

// hardcode sample data
const testimonials = [
  {
    id: 1,
    content:
      "Not A Ghostwriter has transformed my content strategy. The AI captures my voice perfectly, and I save hours each week on content creation.",
    name: "Sarah Johnson",
    role: "Marketing Director",
    company: "TechScale Solutions",
    avatar: "/placeholder.svg?height=64&width=64",
    rating: 5,
  },
  {
    id: 2,
    content:
      "The AI perfectly captures my unique writing style. My audience can't tell the difference between content I wrote myself and what was generated by Not A Ghostwriter.",
    name: "David Chen",
    role: "Social Media Manager",
    company: "Growth Ventures Inc.",
    avatar: "/placeholder.svg?height=64&width=64",
    rating: 5,
  },
  {
    id: 3,
    content:
      "As an enterprise with multiple teams, maintaining consistent voice across content was challenging until we found Not A Ghostwriter. Now our entire organization stays on brand.",
    name: "Michelle Roberts",
    role: "Head of Communications",
    company: "Enterprise Global",
    avatar: "/placeholder.svg?height=64&width=64",
    rating: 5,
  },
];

const pricingPlans = [
  {
    name: "Basic",
    price: "$29",
    description: "Perfect for individuals and small teams",
    features: [
      "20 AI-generated posts per month",
      "1 writing profile",
      "Basic style analysis",
      "Post history (30 days)",
    ],
    cta: "Get Started",
    highlighted: false,
  },
  {
    name: "Professional",
    price: "$79",
    description: "For growing businesses and marketing teams",
    features: [
      "100 AI-generated posts per month",
      "5 writing profiles",
      "Advanced style analysis",
      "Post history (90 days)",
      "Export and scheduling",
      "Priority support",
    ],
    cta: "Try Pro",
    highlighted: true,
  },
  {
    name: "Enterprise",
    price: "Custom",
    description: "For large organizations with advanced needs",
    features: [
      "Unlimited AI-generated posts",
      "Unlimited writing profiles",
      "Team collaboration features",
      "Brand voice consistency",
      "Advanced analytics",
      "API access",
      "Dedicated account manager",
    ],
    cta: "Contact Sales",
    highlighted: false,
  },
];

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      {/* hero */}
      <section className="relative py-24 bg-gradient-to-br from-white to-green-50">
        <div className="absolute inset-0 bg-grid-pattern opacity-5" />
        <div className="container mx-auto px-4 relative">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8">
              <div>
                <div className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-green-100 text-green-800 mb-4">
                  <span className="flex h-2 w-2 rounded-full bg-green-600 mr-2"></span>
                  Trusted by 2,000+ businesses
                </div>
                <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold leading-tight text-gray-900">
                  Content that sounds like{" "}
                  <span className="text-green-800">you</span> wrote it
                </h1>
                <p className="mt-6 text-xl text-gray-600">
                  Generate authentic content that matches your unique writing
                  style and voice with our advanced AI platform.
                </p>
              </div>
              <div className="flex flex-col sm:flex-row gap-4">
                <Button className="bg-green-800 hover:bg-green-900 text-lg py-6 px-8 h-auto">
                  <Link href="/profile" className="flex items-center">
                    Start Free Trial
                    <ArrowRight className="ml-2 h-5 w-5" />
                  </Link>
                </Button>
                <Button
                  asChild
                  variant="outline"
                  className="border-green-800 text-green-800 hover:text-green-900 hover:bg-green-50 text-lg py-6 px-8 h-auto"
                >
                  <Link href="/demo">Watch Demo</Link>
                </Button>
              </div>
              <div className="flex items-center text-sm text-gray-500">
                <Shield className="h-4 w-4 text-green-600 mr-2" />
                <span>No credit card required • 14-day free trial</span>
              </div>
            </div>
            <div className="rounded-xl overflow-hidden shadow-2xl shadow-green-100">
              <Image
                src="/placeholder.svg?height=600&width=800"
                alt="Not A Ghostwriter Dashboard"
                width={800}
                height={600}
                className="w-full h-auto"
              />
            </div>
          </div>

          {/* social proof */}
          <div className="mt-20">
            <p className="text-center text-gray-500 mb-8">
              Trusted by innovative companies
            </p>
            <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-8 items-center justify-items-center opacity-60">
              {[1, 2, 3, 4, 5, 6].map((i) => (
                <div key={i} className="h-8">
                  <Image
                    src={`/placeholder.svg?height=32&width=120&text=LOGO%20${i}`}
                    alt={`Company ${i}`}
                    width={120}
                    height={32}
                  />
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* features */}
      <section className="py-24 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">
              Features designed for authentic content
            </h2>
            <p className="text-xl text-gray-600">
              Our platform helps you create content that resonates with your
              audience and represents your authentic voice.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
            {/* feature 1 */}
            <Card className="border-green-100 shadow-sm">
              <CardContent className="pt-6">
                <div className="bg-green-50 rounded-full w-12 h-12 flex items-center justify-center mb-4">
                  <Users className="h-6 w-6 text-green-800" />
                </div>
                <h3 className="text-xl font-semibold mb-2">
                  Writing Style Analysis
                </h3>
                <p className="text-gray-600">
                  Our AI learns your unique writing style through detailed
                  analysis of your preferences and examples.
                </p>
                <ul className="mt-4 space-y-2">
                  <li className="flex items-start">
                    <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                    <span>Capture tone, voice, and engagement style</span>
                  </li>
                  <li className="flex items-start">
                    <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                    <span>Preserve your unique personality</span>
                  </li>
                  <li className="flex items-start">
                    <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                    <span>Continuously improve with each post</span>
                  </li>
                </ul>
              </CardContent>
            </Card>

            {/* feature 2 */}
            <Card className="border-green-100 shadow-sm">
              <CardContent className="pt-6">
                <div className="bg-green-50 rounded-full w-12 h-12 flex items-center justify-center mb-4">
                  <Award className="h-6 w-6 text-green-800" />
                </div>
                <h3 className="text-xl font-semibold mb-2">
                  Multi-Platform Content
                </h3>
                <p className="text-gray-600">
                  Create authentic content for multiple platforms that drives
                  connection and conversation.
                </p>
                <ul className="mt-4 space-y-2">
                  <li className="flex items-start">
                    <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                    <span>LinkedIn, Twitter, blog posts, and more</span>
                  </li>
                  <li className="flex items-start">
                    <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                    <span>Multiple content lengths and formats</span>
                  </li>
                  <li className="flex items-start">
                    <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                    <span>Control over hashtags and CTAs</span>
                  </li>
                </ul>
              </CardContent>
            </Card>

            {/* feature 3 */}
            <Card className="border-green-100 shadow-sm">
              <CardContent className="pt-6">
                <div className="bg-green-50 rounded-full w-12 h-12 flex items-center justify-center mb-4">
                  <BarChart2 className="h-6 w-6 text-green-800" />
                </div>
                <h3 className="text-xl font-semibold mb-2">
                  Enterprise Team Collaboration
                </h3>
                <p className="text-gray-600">
                  Maintain brand consistency across teams with collaborative
                  tools.
                </p>
                <ul className="mt-4 space-y-2">
                  <li className="flex items-start">
                    <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                    <span>Share writing profiles across teams</span>
                  </li>
                  <li className="flex items-start">
                    <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                    <span>Approval workflows and permissions</span>
                  </li>
                  <li className="flex items-start">
                    <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                    <span>Detailed analytics and reporting</span>
                  </li>
                </ul>
              </CardContent>
            </Card>
          </div>

          <div className="text-center">
            <Button
              asChild
              variant="outline"
              className="border-green-800 text-green-800 hover:text-green-900 hover:bg-green-50"
            >
              <Link href="/features">
                Explore all features <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* how it works */}
      <section className="py-24 bg-green-50">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">How it works</h2>
            <p className="text-xl text-gray-600">
              Create content that sounds like you in just three simple steps
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
            <div className="text-center">
              <div className="w-16 h-16 rounded-full bg-green-200 text-green-800 flex items-center justify-center text-xl font-bold mx-auto mb-4">
                1
              </div>
              <h3 className="text-xl font-semibold mb-2">
                Create your profile
              </h3>
              <p className="text-gray-600">
                Answer questions about your writing style, tone, and preferences
                to create your unique profile.
              </p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 rounded-full bg-green-200 text-green-800 flex items-center justify-center text-xl font-bold mx-auto mb-4">
                2
              </div>
              <h3 className="text-xl font-semibold mb-2">Define your topic</h3>
              <p className="text-gray-600">
                Enter your topic, keywords, and content preferences in our
                simple generation interface.
              </p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 rounded-full bg-green-200 text-green-800 flex items-center justify-center text-xl font-bold mx-auto mb-4">
                3
              </div>
              <h3 className="text-xl font-semibold mb-2">
                Generate and publish
              </h3>
              <p className="text-gray-600">
                Get professionally written content that matches your style,
                ready to copy and share.
              </p>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-lg overflow-hidden">
            <Image
              src="/placeholder.svg?height=500&width=1200&text=Platform%20Workflow%20Demo"
              alt="How Not A Ghostwriter works"
              width={1200}
              height={500}
              className="w-full h-auto"
            />
          </div>
        </div>
      </section>

      {/* testimonials */}
      <section className="py-24 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">What our customers say</h2>
            <p className="text-xl text-gray-600">
              Join thousands of professionals who trust{" "}
              <span className="text-green-800">Not A Ghostwriter</span> for
              their content
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial) => (
              <Card key={testimonial.id} className="border-green-100 shadow-sm">
                <CardContent className="pt-6">
                  <div className="flex items-center mb-4">
                    {[...Array(5)].map((_, i) => (
                      <Star
                        key={i}
                        className={`h-5 w-5 ${
                          i < testimonial.rating
                            ? "text-yellow-400 fill-yellow-400"
                            : "text-gray-300"
                        }`}
                      />
                    ))}
                  </div>
                  <p className="text-gray-700 mb-6">
                    &#34;{testimonial.content}&#34;
                  </p>
                  <div className="flex items-center">
                    <Image
                      src={testimonial.avatar || "/placeholder.svg"}
                      alt={testimonial.name}
                      width={48}
                      height={48}
                      className="rounded-full mr-4"
                    />
                    <div>
                      <h4 className="font-semibold">{testimonial.name}</h4>
                      <p className="text-sm text-gray-500">
                        {testimonial.role}, {testimonial.company}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* pricing */}
      <section
        className="py-24 bg-gradient-to-br from-green-50 to-white"
        id="pricing"
      >
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">
              Simple, transparent pricing
            </h2>
            <p className="text-xl text-gray-600">
              Choose the plan that&#39;s right for your business
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {pricingPlans.map((plan, index) => (
              <div
                key={index}
                className={`rounded-xl overflow-hidden shadow-lg ${
                  plan.highlighted
                    ? "ring-2 ring-green-600 scale-105 bg-white"
                    : "bg-white"
                }`}
              >
                {plan.highlighted && (
                  <div className="bg-green-800 text-white text-center py-2 text-sm font-medium">
                    Most Popular
                  </div>
                )}
                <div className="p-6">
                  <h3 className="text-2xl font-bold">{plan.name}</h3>
                  <div className="mt-4 mb-6">
                    <span className="text-4xl font-bold">{plan.price}</span>
                    {plan.name !== "Enterprise" && (
                      <span className="text-gray-500">/month</span>
                    )}
                  </div>
                  <p className="text-gray-600 mb-6">{plan.description}</p>
                  <Button
                    className={`w-full ${
                      plan.highlighted
                        ? "bg-green-800 hover:bg-green-900"
                        : "bg-gray-100 hover:bg-gray-200 text-gray-800"
                    }`}
                  >
                    <Link
                      href={
                        plan.name === "Enterprise" ? "/contact" : "/profile"
                      }
                    >
                      {plan.cta}
                    </Link>
                  </Button>
                  <ul className="mt-6 space-y-3">
                    {plan.features.map((feature, i) => (
                      <li key={i} className="flex items-start">
                        <Check className="h-5 w-5 text-green-600 mr-2 shrink-0 mt-0.5" />
                        <span>{feature}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-16 text-center">
            <p className="text-gray-600 mb-4">
              Need a custom solution for your enterprise?
            </p>
            <Button
              asChild
              variant="outline"
              className="border-green-800 text-green-800 hover:bg-green-50 hover:text-green-900"
            >
              <Link href="/contact">Contact our sales team</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 bg-green-800">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
              Ready to sound like yourself, without writing it yourself?
            </h2>
            <p className="text-xl text-green-100 mb-8">
              Join thousands of professionals saving time and improving
              engagement with AI-generated content that captures their authentic
              voice.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button className="bg-white text-green-800 hover:bg-gray-100 text-lg py-6 px-8 h-auto">
                <Link href="/profile" className="flex items-center">
                  Start Free Trial
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
              <Button
                asChild
                variant="outline"
                className="border-white bg-green-800 text-white hover:text-white/90 hover:bg-green-700 text-lg py-6 px-8 h-auto"
              >
                <Link href="/demo">Watch Demo</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
